FROM php:7.4
RUN apt-get update -yqq                                                                              
RUN apt-get install git -yqq                                                                         
RUN php bin/composer.phar install